### ISSUE TITLE
Return status-code 1 when process is killed

### ISSUE THREAD

**Issue by hediet** [joaomoreno/deemon#4]
When this happens:
https://github.com/joaomoreno/deemon/blob/cf0bdd809438d0c3d72f39fb4ba6c409c56bfdd2/src/main.ts#L79

This should not exit with status code 0, as the process was killed unexpectedly:
https://github.com/joaomoreno/deemon/blob/cf0bdd809438d0c3d72f39fb4ba6c409c56bfdd2/src/main.ts#L95

This is probably the cause of https://github.com/microsoft/vscode/issues/144246 .

**Comment by joaomoreno** [comment]
You mean something like this? https://github.com/joaomoreno/deemon/pull/5

Maybe all we need is the propagation of the exit code, regardless of when it happens, no?

**Comment by hediet** [comment]
Yep. I guess when deemon receives the kill signal and kills the process, the process will exit with a non-zero exit code.

If that one is forwarded, it will work.

**Comment by joaomoreno** [comment]
Released in deemon@1.7.0

**Comment by hediet** [comment]
Awesome, thank you!
