### ISSUE TITLE
Sometimes killing a deemon doesn’t work in the VS Code build

### ISSUE THREAD

**Issue by TylerLeonhardt** [joaomoreno/deemon#6]
The “Kill VS Code - Build” task doesn't seem always kill the running build task. Often it manages to kill one of 2 running, but not the other.

I’ve noticed this on macOS and some have noticed on Windows.

workaround is to find the deemon process and kill it manually.

Let me know if there’s anything else you need @joaomoreno

**Comment by bpasero** [comment]
Fyi I see this sometimes with the following keyboard shortcut I have configured:

```json
    {
		"key": "cmd+shift+alt+b",
		"command": "workbench.action.tasks.runTask",
		"args": "Restart VS Code - Build"
	}
```

**Comment by joaomoreno** [comment]
I can't really repro. Also, @TylerLeonhardt are you sure this is deemon related? Might actually be VS Code tasks related.

This will kill both tasks from the command line:

```
yarn npm-run-all -lp kill-watch-clientd kill-watch-extensionsd
```

Can you also reproduce if you just run that?

**Comment by TylerLeonhardt** [comment]
Yeah... this must be a task thing I guess because I haven't been able to repro using that script... gonna close this until I have more understanding

**Comment by TylerLeonhardt** [comment]
I was able to reproduce this:

![image](https://user-images.githubusercontent.com/2644648/167212538-4dbaf2bc-3f88-4398-ab90-07abcb1da0ea.png)

left terminal is me running the command manually
right is the Build task that should be killed

**Comment by joaomoreno** [comment]
It killed one but left another running?

**Comment by TylerLeonhardt** [comment]
Yes that's right. And if I run the command over and over again, that surviving process never dies.

Doesn't happen all the time, unfortunately... So I'm not sure what the pattern is.

Any thing else I can grab for you?

**Comment by joaomoreno** [comment]
@hediet and I figured out the issue! Reproduces if you have really long running builds. Fix coming up!

**Comment by yiliang114** [comment]
![image](https://user-images.githubusercontent.com/11473889/200253081-3e5877e5-b551-4e1c-9cca-effc6b50d2b0.png)

I have encountered a problem that deemon cannot kill a task normally. I try to kill for a long time, but it can't end.
Its performance is that I can't recompile the web extensions and I can't kill it. The log it prints out is the last error log, which should no longer exist now, but it is still output and seems to block the entire task. 

hi @joaomoreno, I would like to ask if I have encountered any similar problems ? Or if it has anything to do with this problem?

**Comment by yiliang114** [comment]
> 

This problem appears in mac OS 12.2.1 in intel & deemon@1.7.1

**Comment by joaomoreno** [comment]
thanks for fixing!

**Comment by joaomoreno** [comment]
you got it buddy
