### ISSUE TITLE
Killing a deemon Can't quit in the VS Code build

### ISSUE THREAD

**Issue by yiliang114** [joaomoreno/deemon#8]
Similar to #6 , I comment on that question, now I migrate these here.

![image](https://user-images.githubusercontent.com/11473889/200253081-3e5877e5-b551-4e1c-9cca-effc6b50d2b0.png)

I have encountered a problem that deemon cannot kill a task normally. I try to kill for a long time, but it can't end.
Its performance is that I can't recompile the web extensions and I can't kill it. The log it prints out is the last error log, which should no longer exist now, but it is still output and seems to block the entire task. 

hi @joaomoreno, I would like to ask if I have encountered any similar problems ? Or if it has anything to do with this problem?

This problem appears in mac OS 12.2.1 in intel & deemon@1.7.1

**Comment by joaomoreno** [comment]
How are you killing it? Did you try Ctrl D?

**Comment by yiliang114** [comment]
> How are you killing it? Did you try Ctrl D?

Ctrl D work well, It can exit at the end

**Comment by yiliang114** [comment]
![image](https://user-images.githubusercontent.com/11473889/200316632-78239b0d-fcde-48b8-87eb-f505e178cad1.png)

Just now I found out that it may be the problem of the node process. When I can't kill the tasks started by deemon (the command line is hold on), there are many node processes in the activity monitor. When I kill them all manually, there is no problem with using deemon to start and close the commands.

One of the more embarrassing problems is that since I manually killed the task in the activity monitor, I can't reproduce it.

**Comment by joaomoreno** [comment]
I'm not sure you actually have a problem or are just using deemon incorrectly. Deemon will **not** kill the build task if you quit using <kbd>Ctrl C</kbd>. That's the whole point, it's the reason for using deemon. Pressing <kbd>Ctrl C</kbd> will simply _detatch_ from whatever process it spawned, so you can reconnect to it later using the same command line. If you intend to fully kill the build, then <kbd>Ctrl D</kbd> should be used.
